services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - .:/var/www/html
      - ~/.ssh:/home/laravel/.ssh
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.3-oracle
    container_name: mysql
    restart: unless-stopped
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-laravel}
    volumes:
      - db:/var/lib/mysql
    networks:
      - default

volumes:
  db:

networks:
  default:
    driver: bridge
